[2025-06-05T16:10:27.755+0000] {processor.py:186} INFO - Started process (PID=4600) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:10:27.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-05T16:10:27.759+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:10:27.759+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:10:27.781+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:10:27.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-05T16:10:27.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:10:27.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.071 seconds
[2025-06-05T16:10:58.779+0000] {processor.py:186} INFO - Started process (PID=4665) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:10:58.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-05T16:10:58.784+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:10:58.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:10:58.808+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:10:58.807+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-05T16:10:58.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:10:58.842+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.073 seconds
[2025-06-05T16:11:29.017+0000] {processor.py:186} INFO - Started process (PID=4730) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:11:29.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-05T16:11:29.021+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:11:29.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:11:29.044+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:11:29.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-05T16:11:29.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:11:29.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.069 seconds
[2025-06-05T16:11:59.398+0000] {processor.py:186} INFO - Started process (PID=4795) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:11:59.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-05T16:11:59.401+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:11:59.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:11:59.424+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:11:59.422+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-05T16:11:59.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:11:59.454+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.066 seconds
[2025-06-05T16:12:30.402+0000] {processor.py:186} INFO - Started process (PID=4860) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:12:30.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-05T16:12:30.406+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:12:30.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:12:30.425+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:12:30.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-05T16:12:30.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:12:30.458+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.065 seconds
[2025-06-05T16:13:00.768+0000] {processor.py:186} INFO - Started process (PID=4925) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:13:00.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-05T16:13:00.772+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:13:00.771+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:13:00.794+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:13:00.792+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-05T16:13:00.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:13:00.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.068 seconds
[2025-06-05T16:13:31.337+0000] {processor.py:186} INFO - Started process (PID=4990) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:13:31.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-05T16:13:31.341+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:13:31.340+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:13:31.361+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:13:31.359+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-05T16:13:31.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:13:31.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.065 seconds
[2025-06-05T16:14:02.208+0000] {processor.py:186} INFO - Started process (PID=5055) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:14:02.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-05T16:14:02.212+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:14:02.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:14:02.233+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:14:02.231+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-05T16:14:02.234+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:14:02.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.072 seconds
[2025-06-05T16:14:43.335+0000] {processor.py:186} INFO - Started process (PID=5120) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:14:43.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-05T16:14:43.339+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:14:43.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:14:43.362+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:14:43.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-05T16:14:43.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:14:43.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.071 seconds
[2025-06-05T16:15:13.611+0000] {processor.py:186} INFO - Started process (PID=5185) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:15:13.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-05T16:15:13.614+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:15:13.614+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:15:13.635+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:15:13.633+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-05T16:15:13.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:15:13.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.066 seconds
[2025-06-05T16:15:43.960+0000] {processor.py:186} INFO - Started process (PID=5250) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:15:43.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-05T16:15:43.968+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:15:43.967+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:15:43.996+0000] {logging_mixin.py:190} INFO - [2025-06-05T16:15:43.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-05T16:15:43.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-05T16:15:44.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.101 seconds
